name: set-time-from-plc
version: 0.0.1
summary: ctrlX Data Layer provider for setting system time from plc
title: setting system time from plc
description: |
  ctrlX Data Layer provider for setting system time from plc
base: core20
confinement: strict
grade: stable

apps:
  provider:
    command: bin/main.py
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s 

parts:
  provider:
    plugin: python
    source: .
    stage-packages:
      - libzmq5
      - ctrlx-datalayer
    requirements: [requirements.txt]

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer 
